### ISSUE TITLE
Issue in openActive method

### ISSUE THREAD

**Issue by sandeepbonala** [xevinbox/treemenu.js#2]
When an element is active and has children, if the element is opened by openActive method. The element is having class "tree-opened" but its children are hidden.
Try executing the example here http://xevinbox.github.io/treemenu.js/ by making "Weapons" active.
So, the change need to happen at 
line 38: el.find('> ul').show();
or ignore 45 and 46 lines for the first iteration of while loop.

And also the openActive method is defined twice in latest source code
Let me know if you need more details

**Comment by xevin** [comment]
fixed
